repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.6.4
      hooks:
          - id: aoc-tiles
            args:
                - --auto-add-tiles-to-git=amend
                - --language-sorting=pl,py,go,c,c++
                - --exclude-patterns=*/*.sh
                - --count-as-solved-when=either

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0  # Use the ref you want to point at
        hooks:
        -   id: check-case-conflict
        -   id: detect-private-key
        -   id: end-of-file-fixer
        # -   id: ...
